# Generated by Django 5.0.6 on 2024-07-27 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='staff_mob',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='staff_name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
