# Generated by Django 5.0.6 on 2024-07-17 07:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('department_id', models.AutoField(primary_key=True, serialize=False)),
                ('department_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ExamNotice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=255)),
                ('main_content', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='exam_notices/')),
                ('document', models.FileField(blank=True, null=True, upload_to='exam_notices/')),
                ('sem', models.IntegerField()),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='GeneralNotice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=255)),
                ('main_content', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='notices/')),
                ('document', models.FileField(blank=True, null=True, upload_to='notices/')),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='AcademicNotice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=255)),
                ('main_content', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='academic_notices/')),
                ('document', models.FileField(blank=True, null=True, upload_to='academic_notices/')),
                ('sem', models.IntegerField()),
                ('date', models.DateField()),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dnbapp.department')),
            ],
        ),
        migrations.CreateModel(
            name='DepartmentNotice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=255)),
                ('main_content', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='department_notices/')),
                ('document', models.FileField(blank=True, null=True, upload_to='department_notices/')),
                ('sem', models.IntegerField()),
                ('date', models.DateField()),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dnbapp.department')),
            ],
        ),
        migrations.CreateModel(
            name='PlacementNotice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=255)),
                ('main_content', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='placement_notices/')),
                ('document', models.FileField(blank=True, null=True, upload_to='placement_notices/')),
                ('sem', models.IntegerField()),
                ('organisation', models.CharField(max_length=255)),
                ('specific_details', models.TextField()),
                ('date', models.DateField()),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dnbapp.department')),
            ],
        ),
    ]
