# Generated by Django 5.0.6 on 2024-07-19 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dnbapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicnotice',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='departmentnotice',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='examnotice',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='generalnotice',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='placementnotice',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
